### ISSUE TITLE
[Feat]Merge and report the results of shard execution

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/octocov-runn-coverage#5]
refs https://github.com/k1LoW/runn/issues/747

example
```console
$ runn coverage --scopes run:exec --label shard1  path/to/**/*.yml > shard1.json
$ runn coverage --scopes run:exec --label shard2  path/to/**/*.yml > shard2.json
$ octocov-runn-coverage merge shard1.json shard2.json
```

**Comment by k1LoW** [comment]
@k2tzumi Thank you for your request.

`runn coverage` is a command to check static coverage. Why bother to separate them and then merge them further?

**Comment by k2tzumi** [comment]
The number of scenarios is too large and takes too long to execute. But we also want to look at coverage at regular intervals.
I would like to realize the following PRs once they are addressed.
https://github.com/k1LoW/runn/issues/748

**Comment by k2tzumi** [comment]
I understand what you mean by static coverage.
https://github.com/k1LoW/runn/issues/748#issuecomment-1890824839
